--- Script to create a new table with a primary key

--- Create table
IF OBJECT_ID('dbo.MYTABLE') IS NOT NULL
BEGIN
    DROP TABLE dbo.MYTABLE;
END;
CREATE TABLE dbo.MYTABLE
(
    MYCOLUMN1 BIGINT NOT NULL,
    MYCOLUMN2 VARCHAR(100) NOT NULL,
    CONSTRAINT PK_dbo_MYTABLE
        PRIMARY KEY CLUSTERED (MYCOLUMN1) ON [PRIMARY]
) ON [PRIMARY];
GO
--- Insert data
INSERT INTO dbo.MYTABLE
(
    MYCOLUMN1,
    MYCOLUMN2
)
SELECT MYOTHERCOLUMN1,
       MYOTHERCOLUMN2
FROM dbo.MYOTHERTABLE;